language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode10.2

before_install: .travis/install-deps.sh

install: .travis/install.sh

script:
- find . -name "*.sh" -print0 | xargs -0 -n1 shellcheck
- find . -name "*.sh" -print0 | xargs -0 -n1 bashate
- find . -name "*.py" -print0 | xargs -0 -n1 flake8
- find ansible -name "*.yml" -print0 | xargs -0 -n1 ansible-lint -x 503
- foodcritic chef/cookbooks
- cookstyle .
#- pytest
