- import_tasks: register-compute-nodes.yml
  become: true
  run_once: true
  tags: [never,register-compute-nodes]

- import_tasks: cloud-images.yml
  become: true
  run_once: true
  tags: [never,add-cloud-images]

- import_tasks: adjust-ceph-pool-pgs.yml
  become: true
  run_once: true
  tags: [never,adjust-ceph-pool-pgs]

- import_tasks: configure-host-aggregates.yml
  become: true
  run_once: true
  tags: [never,configure-host-aggregates]
